# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.define "devstack4" do |dev|

    config.vm.network "private_network", ip: "192.168.50.10"
    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = "4"
    end
  end
  config.vm.provision "shell", path: "install-script-v4.sh"
end
